services:
  - type: web
    name: trading-journal-backend
    env: python
    build:
      command: |
        pip install -r requirements.txt
      publish: backend/
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: trading-journal-db
          property: connectionString
    plan: free

databases:
  - name: trading-journal-db
    databaseName: trading_journal
    user: trading_journal_user
    plan: free
